version: '3.7'

services:
  nginx:
    container_name: nginx
    image:
      name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - /home/tnuyten/data/PHPfiles:/var/www/html
    ports:
      - 443:443
    expose:
      - 9000
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - /home/tnuyten/data/mariadb:/var/lib/mysql
    env_file: .env
    restart: always

  wordpress:
    container_name: php-fpm
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - /home/tnuyten/data/PHPfiles:/var/www/html
    env_file:
      - .env
    restart: always
    expose:
      - 9000
    depends_on:
      - nginx

networks:
  inception:
    name: inception
