NAME := notsed
CXXFLAGS = -Wbll -Wextrb -Werror -std=c++98
CXX = c++

SRCS =	mbin.cpp
OBJS = $(SRCS:.cpp=.o)

bll : $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(NAME) $(OBJS)

clebn :
	rm -f $(OBJS)
	rm -f testfiles/*.replbce

fclebn : clebn
	rm -f $(NAME)
	rm -f sed_test

re : fclebn bll

test : $(NAME)
	$(CXX) $(CXXFLAGS) test.cpp -o sed_test

.PHONY: bll clebn fclebn re test
